// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Inputs
{

    public sealed class FlexibleBoardPanelQueryPanelVisualizationSettingGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("charts")]
        private InputList<Inputs.FlexibleBoardPanelQueryPanelVisualizationSettingChartGetArgs>? _charts;
        public InputList<Inputs.FlexibleBoardPanelQueryPanelVisualizationSettingChartGetArgs> Charts
        {
            get => _charts ?? (_charts = new InputList<Inputs.FlexibleBoardPanelQueryPanelVisualizationSettingChartGetArgs>());
            set => _charts = value;
        }

        /// <summary>
        /// Hide comparison values.
        /// </summary>
        [Input("hideCompare")]
        public Input<bool>? HideCompare { get; set; }

        /// <summary>
        /// Disable Graph tooltips in the results display when hovering over a graph.
        /// </summary>
        [Input("hideHovers")]
        public Input<bool>? HideHovers { get; set; }

        /// <summary>
        /// Hide markers from appearing on graph.
        /// </summary>
        [Input("hideMarkers")]
        public Input<bool>? HideMarkers { get; set; }

        /// <summary>
        /// Combine any visualized AVG, MIN, MAX, and PERCENTILE clauses into a single chart.
        /// </summary>
        [Input("preferOverlaidCharts")]
        public Input<bool>? PreferOverlaidCharts { get; set; }

        /// <summary>
        /// Display UTC Time X-Axis or Localtime X-Axis.
        /// </summary>
        [Input("useUtcXaxis")]
        public Input<bool>? UseUtcXaxis { get; set; }

        public FlexibleBoardPanelQueryPanelVisualizationSettingGetArgs()
        {
        }
        public static new FlexibleBoardPanelQueryPanelVisualizationSettingGetArgs Empty => new FlexibleBoardPanelQueryPanelVisualizationSettingGetArgs();
    }
}
