// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Inputs
{

    public sealed class FlexibleBoardPanelQueryPanelVisualizationSettingChartGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Index of the chart this configuration controls.
        /// </summary>
        [Input("chartIndex")]
        public Input<double>? ChartIndex { get; set; }

        /// <summary>
        /// Type of chart (e.g., 'line', 'bar').
        /// </summary>
        [Input("chartType")]
        public Input<string>? ChartType { get; set; }

        /// <summary>
        /// Omit missing values from the visualization.
        /// </summary>
        [Input("omitMissingValues")]
        public Input<bool>? OmitMissingValues { get; set; }

        /// <summary>
        /// Use logarithmic scale on Y axis.
        /// </summary>
        [Input("useLogScale")]
        public Input<bool>? UseLogScale { get; set; }

        public FlexibleBoardPanelQueryPanelVisualizationSettingChartGetArgs()
        {
        }
        public static new FlexibleBoardPanelQueryPanelVisualizationSettingChartGetArgs Empty => new FlexibleBoardPanelQueryPanelVisualizationSettingChartGetArgs();
    }
}
