// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Inputs
{

    public sealed class FlexibleBoardPanelSloPanelGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// SLO ID to display in this panel.
        /// </summary>
        [Input("sloId", required: true)]
        public Input<string> SloId { get; set; } = null!;

        public FlexibleBoardPanelSloPanelGetArgs()
        {
        }
        public static new FlexibleBoardPanelSloPanelGetArgs Empty => new FlexibleBoardPanelSloPanelGetArgs();
    }
}
