// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Inputs
{

    public sealed class FlexibleBoardPanelPositionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The height of the panel.
        /// </summary>
        [Input("height")]
        public Input<double>? Height { get; set; }

        /// <summary>
        /// The width of the panel.
        /// </summary>
        [Input("width")]
        public Input<double>? Width { get; set; }

        /// <summary>
        /// The X coordinate of the panel.
        /// </summary>
        [Input("xCoordinate")]
        public Input<double>? XCoordinate { get; set; }

        /// <summary>
        /// The Y coordinate of the panel.
        /// </summary>
        [Input("yCoordinate")]
        public Input<double>? YCoordinate { get; set; }

        public FlexibleBoardPanelPositionArgs()
        {
        }
        public static new FlexibleBoardPanelPositionArgs Empty => new FlexibleBoardPanelPositionArgs();
    }
}
