// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Inputs
{

    public sealed class FlexibleBoardPanelArgs : global::Pulumi.ResourceArgs
    {
        [Input("positions")]
        private InputList<Inputs.FlexibleBoardPanelPositionArgs>? _positions;

        /// <summary>
        /// Manages the position of the panel on the board.
        /// </summary>
        public InputList<Inputs.FlexibleBoardPanelPositionArgs> Positions
        {
            get => _positions ?? (_positions = new InputList<Inputs.FlexibleBoardPanelPositionArgs>());
            set => _positions = value;
        }

        [Input("queryPanels")]
        private InputList<Inputs.FlexibleBoardPanelQueryPanelArgs>? _queryPanels;

        /// <summary>
        /// A query panel to be displayed on the Board.
        /// </summary>
        public InputList<Inputs.FlexibleBoardPanelQueryPanelArgs> QueryPanels
        {
            get => _queryPanels ?? (_queryPanels = new InputList<Inputs.FlexibleBoardPanelQueryPanelArgs>());
            set => _queryPanels = value;
        }

        [Input("sloPanels")]
        private InputList<Inputs.FlexibleBoardPanelSloPanelArgs>? _sloPanels;

        /// <summary>
        /// A Service Level Objective(SLO) panel to be displayed on the Board.
        /// </summary>
        public InputList<Inputs.FlexibleBoardPanelSloPanelArgs> SloPanels
        {
            get => _sloPanels ?? (_sloPanels = new InputList<Inputs.FlexibleBoardPanelSloPanelArgs>());
            set => _sloPanels = value;
        }

        /// <summary>
        /// The panel type, either "query" or "slo".
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public FlexibleBoardPanelArgs()
        {
        }
        public static new FlexibleBoardPanelArgs Empty => new FlexibleBoardPanelArgs();
    }
}
