// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Inputs
{

    public sealed class GetAuthMetadataEnvironmentArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Whether the Environment is a Classic Environment.
        /// </summary>
        [Input("classic", required: true)]
        public bool Classic { get; set; }

        /// <summary>
        /// The name of the Environment. For Classic environments, this will be null.
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        /// <summary>
        /// The slug of the Environment. For Classic environments, this will be null.
        /// </summary>
        [Input("slug", required: true)]
        public string Slug { get; set; } = null!;

        public GetAuthMetadataEnvironmentArgs()
        {
        }
        public static new GetAuthMetadataEnvironmentArgs Empty => new GetAuthMetadataEnvironmentArgs();
    }
}
