// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Inputs
{

    public sealed class GetAuthMetadataApiKeyAccessInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether this API key can create and manage Boards.
        /// </summary>
        [Input("boards", required: true)]
        public Input<bool> Boards { get; set; } = null!;

        /// <summary>
        /// Whether this API key can create and manage Queries, Columns, Derived Columns, and Query Annotations.
        /// </summary>
        [Input("columns", required: true)]
        public Input<bool> Columns { get; set; } = null!;

        /// <summary>
        /// Whether this API key can create and manage Datasets.
        /// </summary>
        [Input("datasets", required: true)]
        public Input<bool> Datasets { get; set; } = null!;

        /// <summary>
        /// Whether this API key can send events to Honeycomb.
        /// </summary>
        [Input("events", required: true)]
        public Input<bool> Events { get; set; } = null!;

        /// <summary>
        /// Whether this API key can create and manage Markers.
        /// </summary>
        [Input("markers", required: true)]
        public Input<bool> Markers { get; set; } = null!;

        /// <summary>
        /// Whether this API key can execute existing Queries via the Query Data API.
        /// </summary>
        [Input("queries", required: true)]
        public Input<bool> Queries { get; set; } = null!;

        /// <summary>
        /// Whether this API key can create and manage Recipients.
        /// </summary>
        [Input("recipients", required: true)]
        public Input<bool> Recipients { get; set; } = null!;

        /// <summary>
        /// Whether this API key can create and manage SLOs and Burn Alerts.
        /// </summary>
        [Input("slos", required: true)]
        public Input<bool> Slos { get; set; } = null!;

        /// <summary>
        /// Whether this API key can create and manage Triggers.
        /// </summary>
        [Input("triggers", required: true)]
        public Input<bool> Triggers { get; set; } = null!;

        public GetAuthMetadataApiKeyAccessInputArgs()
        {
        }
        public static new GetAuthMetadataApiKeyAccessInputArgs Empty => new GetAuthMetadataApiKeyAccessInputArgs();
    }
}
