// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Inputs
{

    public sealed class GetQuerySpecificationCalculationArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The column to apply the operator on. Not allowed with "COUNT" or "CONCURRENCY", required for all other operators.
        /// </summary>
        [Input("column")]
        public string? Column { get; set; }

        /// <summary>
        /// The operatior to apply.
        /// </summary>
        [Input("op", required: true)]
        public string Op { get; set; } = null!;

        public GetQuerySpecificationCalculationArgs()
        {
        }
        public static new GetQuerySpecificationCalculationArgs Empty => new GetQuerySpecificationCalculationArgs();
    }
}
