// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Inputs
{

    public sealed class GetQuerySpecificationHavingInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The operator to apply.
        /// </summary>
        [Input("calculateOp", required: true)]
        public Input<string> CalculateOp { get; set; } = null!;

        /// <summary>
        /// The column to filter on. Not allowed with "COUNT".
        /// </summary>
        [Input("column")]
        public Input<string>? Column { get; set; }

        /// <summary>
        /// The operator to apply.
        /// </summary>
        [Input("op", required: true)]
        public Input<string> Op { get; set; } = null!;

        /// <summary>
        /// The value used for the filter.
        /// </summary>
        [Input("value", required: true)]
        public Input<double> Value { get; set; } = null!;

        public GetQuerySpecificationHavingInputArgs()
        {
        }
        public static new GetQuerySpecificationHavingInputArgs Empty => new GetQuerySpecificationHavingInputArgs();
    }
}
