// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Inputs
{

    public sealed class GetQuerySpecificationFilterInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The column to filter on.
        /// </summary>
        [Input("column", required: true)]
        public Input<string> Column { get; set; } = null!;

        /// <summary>
        /// The operator to apply.
        /// </summary>
        [Input("op", required: true)]
        public Input<string> Op { get; set; } = null!;

        /// <summary>
        /// The value used for the filter. Not needed if op is "exists" or "not-exists".
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public GetQuerySpecificationFilterInputArgs()
        {
        }
        public static new GetQuerySpecificationFilterInputArgs Empty => new GetQuerySpecificationFilterInputArgs();
    }
}
