// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Inputs
{

    public sealed class GetQuerySpecificationHavingArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The operator to apply.
        /// </summary>
        [Input("calculateOp", required: true)]
        public string CalculateOp { get; set; } = null!;

        /// <summary>
        /// The column to filter on. Not allowed with "COUNT".
        /// </summary>
        [Input("column")]
        public string? Column { get; set; }

        /// <summary>
        /// The operator to apply.
        /// </summary>
        [Input("op", required: true)]
        public string Op { get; set; } = null!;

        /// <summary>
        /// The value used for the filter.
        /// </summary>
        [Input("value", required: true)]
        public double Value { get; set; }

        public GetQuerySpecificationHavingArgs()
        {
        }
        public static new GetQuerySpecificationHavingArgs Empty => new GetQuerySpecificationHavingArgs();
    }
}
