// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Inputs
{

    public sealed class TriggerBaselineDetailArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// What previous time period to evaluate against: 1 hour, 1 day, 1 week, or 4 weeks.
        /// </summary>
        [Input("offsetMinutes", required: true)]
        public Input<double> OffsetMinutes { get; set; } = null!;

        /// <summary>
        /// Whether to use an absolute value or percentage delta.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public TriggerBaselineDetailArgs()
        {
        }
        public static new TriggerBaselineDetailArgs Empty => new TriggerBaselineDetailArgs();
    }
}
