// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Inputs
{

    public sealed class TriggerRecipientNotificationDetailGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The severity to set with the PagerDuty notification. If no severity is provided, 'critical' is assumed.
        /// </summary>
        [Input("pagerdutySeverity")]
        public Input<string>? PagerdutySeverity { get; set; }

        [Input("variables")]
        private InputList<Inputs.TriggerRecipientNotificationDetailVariableGetArgs>? _variables;

        /// <summary>
        /// The variables to set with the webhook notification.
        /// </summary>
        public InputList<Inputs.TriggerRecipientNotificationDetailVariableGetArgs> Variables
        {
            get => _variables ?? (_variables = new InputList<Inputs.TriggerRecipientNotificationDetailVariableGetArgs>());
            set => _variables = value;
        }

        public TriggerRecipientNotificationDetailGetArgs()
        {
        }
        public static new TriggerRecipientNotificationDetailGetArgs Empty => new TriggerRecipientNotificationDetailGetArgs();
    }
}
