// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Inputs
{

    public sealed class WebhookRecipientVariableArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// An optional default value for the variable
        /// </summary>
        [Input("defaultValue")]
        public Input<string>? DefaultValue { get; set; }

        /// <summary>
        /// The name of the variable
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public WebhookRecipientVariableArgs()
        {
        }
        public static new WebhookRecipientVariableArgs Empty => new WebhookRecipientVariableArgs();
    }
}
