// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio
{
    [HoneycombioResourceType("honeycombio:index/emailRecipient:EmailRecipient")]
    public partial class EmailRecipient : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The email address to send the notification to
        /// </summary>
        [Output("address")]
        public Output<string> Address { get; private set; } = null!;

        [Output("emailRecipientId")]
        public Output<string> EmailRecipientId { get; private set; } = null!;


        /// <summary>
        /// Create a EmailRecipient resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public EmailRecipient(string name, EmailRecipientArgs args, CustomResourceOptions? options = null)
            : base("honeycombio:index/emailRecipient:EmailRecipient", name, args ?? new EmailRecipientArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private EmailRecipient(string name, Input<string> id, EmailRecipientState? state = null, CustomResourceOptions? options = null)
            : base("honeycombio:index/emailRecipient:EmailRecipient", name, state, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing EmailRecipient resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static EmailRecipient Get(string name, Input<string> id, EmailRecipientState? state = null, CustomResourceOptions? options = null)
        {
            return new EmailRecipient(name, id, state, options);
        }
    }

    public sealed class EmailRecipientArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The email address to send the notification to
        /// </summary>
        [Input("address", required: true)]
        public Input<string> Address { get; set; } = null!;

        [Input("emailRecipientId")]
        public Input<string>? EmailRecipientId { get; set; }

        public EmailRecipientArgs()
        {
        }
        public static new EmailRecipientArgs Empty => new EmailRecipientArgs();
    }

    public sealed class EmailRecipientState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The email address to send the notification to
        /// </summary>
        [Input("address")]
        public Input<string>? Address { get; set; }

        [Input("emailRecipientId")]
        public Input<string>? EmailRecipientId { get; set; }

        public EmailRecipientState()
        {
        }
        public static new EmailRecipientState Empty => new EmailRecipientState();
    }
}
