// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio
{
    public static class GetDerivedColumn
    {
        public static Task<GetDerivedColumnResult> InvokeAsync(GetDerivedColumnArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDerivedColumnResult>("honeycombio:index/getDerivedColumn:getDerivedColumn", args ?? new GetDerivedColumnArgs(), options.WithDefaults(), Utilities.PackageParameterization());

        public static Output<GetDerivedColumnResult> Invoke(GetDerivedColumnInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDerivedColumnResult>("honeycombio:index/getDerivedColumn:getDerivedColumn", args ?? new GetDerivedColumnInvokeArgs(), options.WithDefaults());

        public static Output<GetDerivedColumnResult> Invoke(GetDerivedColumnInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetDerivedColumnResult>("honeycombio:index/getDerivedColumn:getDerivedColumn", args ?? new GetDerivedColumnInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDerivedColumnArgs : global::Pulumi.InvokeArgs
    {
        [Input("alias", required: true)]
        public string Alias { get; set; } = null!;

        [Input("dataset")]
        public string? Dataset { get; set; }

        public GetDerivedColumnArgs()
        {
        }
        public static new GetDerivedColumnArgs Empty => new GetDerivedColumnArgs();
    }

    public sealed class GetDerivedColumnInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("alias", required: true)]
        public Input<string> Alias { get; set; } = null!;

        [Input("dataset")]
        public Input<string>? Dataset { get; set; }

        public GetDerivedColumnInvokeArgs()
        {
        }
        public static new GetDerivedColumnInvokeArgs Empty => new GetDerivedColumnInvokeArgs();
    }


    [OutputType]
    public sealed class GetDerivedColumnResult
    {
        public readonly string Alias;
        public readonly string? Dataset;
        public readonly string Description;
        public readonly string Expression;
        public readonly string Id;

        [OutputConstructor]
        private GetDerivedColumnResult(
            string alias,

            string? dataset,

            string description,

            string expression,

            string id)
        {
            Alias = alias;
            Dataset = dataset;
            Description = description;
            Expression = expression;
            Id = id;
        }
    }
}
