// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio
{
    public static class GetEnvironment
    {
        public static Task<GetEnvironmentResult> InvokeAsync(GetEnvironmentArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetEnvironmentResult>("honeycombio:index/getEnvironment:getEnvironment", args ?? new GetEnvironmentArgs(), options.WithDefaults(), Utilities.PackageParameterization());

        public static Output<GetEnvironmentResult> Invoke(GetEnvironmentInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetEnvironmentResult>("honeycombio:index/getEnvironment:getEnvironment", args ?? new GetEnvironmentInvokeArgs(), options.WithDefaults());

        public static Output<GetEnvironmentResult> Invoke(GetEnvironmentInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetEnvironmentResult>("honeycombio:index/getEnvironment:getEnvironment", args ?? new GetEnvironmentInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetEnvironmentArgs : global::Pulumi.InvokeArgs
    {
        [Input("detailFilters")]
        private List<Inputs.GetEnvironmentDetailFilterArgs>? _detailFilters;
        public List<Inputs.GetEnvironmentDetailFilterArgs> DetailFilters
        {
            get => _detailFilters ?? (_detailFilters = new List<Inputs.GetEnvironmentDetailFilterArgs>());
            set => _detailFilters = value;
        }

        [Input("id")]
        public string? Id { get; set; }

        public GetEnvironmentArgs()
        {
        }
        public static new GetEnvironmentArgs Empty => new GetEnvironmentArgs();
    }

    public sealed class GetEnvironmentInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("detailFilters")]
        private InputList<Inputs.GetEnvironmentDetailFilterInputArgs>? _detailFilters;
        public InputList<Inputs.GetEnvironmentDetailFilterInputArgs> DetailFilters
        {
            get => _detailFilters ?? (_detailFilters = new InputList<Inputs.GetEnvironmentDetailFilterInputArgs>());
            set => _detailFilters = value;
        }

        [Input("id")]
        public Input<string>? Id { get; set; }

        public GetEnvironmentInvokeArgs()
        {
        }
        public static new GetEnvironmentInvokeArgs Empty => new GetEnvironmentInvokeArgs();
    }


    [OutputType]
    public sealed class GetEnvironmentResult
    {
        public readonly string Color;
        public readonly bool DeleteProtected;
        public readonly string Description;
        public readonly ImmutableArray<Outputs.GetEnvironmentDetailFilterResult> DetailFilters;
        public readonly string Id;
        public readonly string Name;
        public readonly string Slug;

        [OutputConstructor]
        private GetEnvironmentResult(
            string color,

            bool deleteProtected,

            string description,

            ImmutableArray<Outputs.GetEnvironmentDetailFilterResult> detailFilters,

            string id,

            string name,

            string slug)
        {
            Color = color;
            DeleteProtected = deleteProtected;
            Description = description;
            DetailFilters = detailFilters;
            Id = id;
            Name = name;
            Slug = slug;
        }
    }
}
