// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio
{
    public static class GetTriggerRecipient
    {
        public static Task<GetTriggerRecipientResult> InvokeAsync(GetTriggerRecipientArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetTriggerRecipientResult>("honeycombio:index/getTriggerRecipient:getTriggerRecipient", args ?? new GetTriggerRecipientArgs(), options.WithDefaults(), Utilities.PackageParameterization());

        public static Output<GetTriggerRecipientResult> Invoke(GetTriggerRecipientInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetTriggerRecipientResult>("honeycombio:index/getTriggerRecipient:getTriggerRecipient", args ?? new GetTriggerRecipientInvokeArgs(), options.WithDefaults());

        public static Output<GetTriggerRecipientResult> Invoke(GetTriggerRecipientInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetTriggerRecipientResult>("honeycombio:index/getTriggerRecipient:getTriggerRecipient", args ?? new GetTriggerRecipientInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetTriggerRecipientArgs : global::Pulumi.InvokeArgs
    {
        [Input("dataset", required: true)]
        public string Dataset { get; set; } = null!;

        [Input("id")]
        public string? Id { get; set; }

        [Input("target")]
        public string? Target { get; set; }

        [Input("type", required: true)]
        public string Type { get; set; } = null!;

        public GetTriggerRecipientArgs()
        {
        }
        public static new GetTriggerRecipientArgs Empty => new GetTriggerRecipientArgs();
    }

    public sealed class GetTriggerRecipientInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("dataset", required: true)]
        public Input<string> Dataset { get; set; } = null!;

        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("target")]
        public Input<string>? Target { get; set; }

        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public GetTriggerRecipientInvokeArgs()
        {
        }
        public static new GetTriggerRecipientInvokeArgs Empty => new GetTriggerRecipientInvokeArgs();
    }


    [OutputType]
    public sealed class GetTriggerRecipientResult
    {
        public readonly string Dataset;
        public readonly string Id;
        public readonly string? Target;
        public readonly string Type;

        [OutputConstructor]
        private GetTriggerRecipientResult(
            string dataset,

            string id,

            string? target,

            string type)
        {
            Dataset = dataset;
            Id = id;
            Target = target;
            Type = type;
        }
    }
}
