// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio
{
    [HoneycombioResourceType("honeycombio:index/datasetDefinition:DatasetDefinition")]
    public partial class DatasetDefinition : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The column to set the definition to. Must be the name of an existing Column or the alias of an existing Derived Column.
        /// </summary>
        [Output("column")]
        public Output<string> Column { get; private set; } = null!;

        /// <summary>
        /// The type of the column assigned to the definition. Either `column` or `derived_column`.
        /// </summary>
        [Output("columnType")]
        public Output<string> ColumnType { get; private set; } = null!;

        /// <summary>
        /// The dataset to set the Dataset Definition for.
        /// </summary>
        [Output("dataset")]
        public Output<string> Dataset { get; private set; } = null!;

        [Output("datasetDefinitionId")]
        public Output<string> DatasetDefinitionId { get; private set; } = null!;

        /// <summary>
        /// The name of the definition being set.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;


        /// <summary>
        /// Create a DatasetDefinition resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DatasetDefinition(string name, DatasetDefinitionArgs args, CustomResourceOptions? options = null)
            : base("honeycombio:index/datasetDefinition:DatasetDefinition", name, args ?? new DatasetDefinitionArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private DatasetDefinition(string name, Input<string> id, DatasetDefinitionState? state = null, CustomResourceOptions? options = null)
            : base("honeycombio:index/datasetDefinition:DatasetDefinition", name, state, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DatasetDefinition resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DatasetDefinition Get(string name, Input<string> id, DatasetDefinitionState? state = null, CustomResourceOptions? options = null)
        {
            return new DatasetDefinition(name, id, state, options);
        }
    }

    public sealed class DatasetDefinitionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The column to set the definition to. Must be the name of an existing Column or the alias of an existing Derived Column.
        /// </summary>
        [Input("column", required: true)]
        public Input<string> Column { get; set; } = null!;

        /// <summary>
        /// The dataset to set the Dataset Definition for.
        /// </summary>
        [Input("dataset", required: true)]
        public Input<string> Dataset { get; set; } = null!;

        [Input("datasetDefinitionId")]
        public Input<string>? DatasetDefinitionId { get; set; }

        /// <summary>
        /// The name of the definition being set.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public DatasetDefinitionArgs()
        {
        }
        public static new DatasetDefinitionArgs Empty => new DatasetDefinitionArgs();
    }

    public sealed class DatasetDefinitionState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The column to set the definition to. Must be the name of an existing Column or the alias of an existing Derived Column.
        /// </summary>
        [Input("column")]
        public Input<string>? Column { get; set; }

        /// <summary>
        /// The type of the column assigned to the definition. Either `column` or `derived_column`.
        /// </summary>
        [Input("columnType")]
        public Input<string>? ColumnType { get; set; }

        /// <summary>
        /// The dataset to set the Dataset Definition for.
        /// </summary>
        [Input("dataset")]
        public Input<string>? Dataset { get; set; }

        [Input("datasetDefinitionId")]
        public Input<string>? DatasetDefinitionId { get; set; }

        /// <summary>
        /// The name of the definition being set.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public DatasetDefinitionState()
        {
        }
        public static new DatasetDefinitionState Empty => new DatasetDefinitionState();
    }
}
