// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio
{
    public static class GetColumn
    {
        public static Task<GetColumnResult> InvokeAsync(GetColumnArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetColumnResult>("honeycombio:index/getColumn:getColumn", args ?? new GetColumnArgs(), options.WithDefaults(), Utilities.PackageParameterization());

        public static Output<GetColumnResult> Invoke(GetColumnInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetColumnResult>("honeycombio:index/getColumn:getColumn", args ?? new GetColumnInvokeArgs(), options.WithDefaults());

        public static Output<GetColumnResult> Invoke(GetColumnInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetColumnResult>("honeycombio:index/getColumn:getColumn", args ?? new GetColumnInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetColumnArgs : global::Pulumi.InvokeArgs
    {
        [Input("dataset", required: true)]
        public string Dataset { get; set; } = null!;

        [Input("id")]
        public string? Id { get; set; }

        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetColumnArgs()
        {
        }
        public static new GetColumnArgs Empty => new GetColumnArgs();
    }

    public sealed class GetColumnInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("dataset", required: true)]
        public Input<string> Dataset { get; set; } = null!;

        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetColumnInvokeArgs()
        {
        }
        public static new GetColumnInvokeArgs Empty => new GetColumnInvokeArgs();
    }


    [OutputType]
    public sealed class GetColumnResult
    {
        public readonly string CreatedAt;
        public readonly string Dataset;
        public readonly string Description;
        public readonly bool Hidden;
        public readonly string Id;
        public readonly string LastWrittenAt;
        public readonly string Name;
        public readonly string Type;
        public readonly string UpdatedAt;

        [OutputConstructor]
        private GetColumnResult(
            string createdAt,

            string dataset,

            string description,

            bool hidden,

            string id,

            string lastWrittenAt,

            string name,

            string type,

            string updatedAt)
        {
            CreatedAt = createdAt;
            Dataset = dataset;
            Description = description;
            Hidden = hidden;
            Id = id;
            LastWrittenAt = lastWrittenAt;
            Name = name;
            Type = type;
            UpdatedAt = updatedAt;
        }
    }
}
