// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio
{
    public static class GetDerivedColumns
    {
        public static Task<GetDerivedColumnsResult> InvokeAsync(GetDerivedColumnsArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDerivedColumnsResult>("honeycombio:index/getDerivedColumns:getDerivedColumns", args ?? new GetDerivedColumnsArgs(), options.WithDefaults(), Utilities.PackageParameterization());

        public static Output<GetDerivedColumnsResult> Invoke(GetDerivedColumnsInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDerivedColumnsResult>("honeycombio:index/getDerivedColumns:getDerivedColumns", args ?? new GetDerivedColumnsInvokeArgs(), options.WithDefaults());

        public static Output<GetDerivedColumnsResult> Invoke(GetDerivedColumnsInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetDerivedColumnsResult>("honeycombio:index/getDerivedColumns:getDerivedColumns", args ?? new GetDerivedColumnsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDerivedColumnsArgs : global::Pulumi.InvokeArgs
    {
        [Input("dataset")]
        public string? Dataset { get; set; }

        [Input("startsWith")]
        public string? StartsWith { get; set; }

        public GetDerivedColumnsArgs()
        {
        }
        public static new GetDerivedColumnsArgs Empty => new GetDerivedColumnsArgs();
    }

    public sealed class GetDerivedColumnsInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("dataset")]
        public Input<string>? Dataset { get; set; }

        [Input("startsWith")]
        public Input<string>? StartsWith { get; set; }

        public GetDerivedColumnsInvokeArgs()
        {
        }
        public static new GetDerivedColumnsInvokeArgs Empty => new GetDerivedColumnsInvokeArgs();
    }


    [OutputType]
    public sealed class GetDerivedColumnsResult
    {
        public readonly string? Dataset;
        public readonly string Id;
        public readonly ImmutableArray<string> Names;
        public readonly string? StartsWith;

        [OutputConstructor]
        private GetDerivedColumnsResult(
            string? dataset,

            string id,

            ImmutableArray<string> names,

            string? startsWith)
        {
            Dataset = dataset;
            Id = id;
            Names = names;
            StartsWith = startsWith;
        }
    }
}
