// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio
{
    public static class GetSlos
    {
        public static Task<GetSlosResult> InvokeAsync(GetSlosArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSlosResult>("honeycombio:index/getSlos:getSlos", args ?? new GetSlosArgs(), options.WithDefaults(), Utilities.PackageParameterization());

        public static Output<GetSlosResult> Invoke(GetSlosInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSlosResult>("honeycombio:index/getSlos:getSlos", args ?? new GetSlosInvokeArgs(), options.WithDefaults());

        public static Output<GetSlosResult> Invoke(GetSlosInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetSlosResult>("honeycombio:index/getSlos:getSlos", args ?? new GetSlosInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSlosArgs : global::Pulumi.InvokeArgs
    {
        [Input("dataset")]
        public string? Dataset { get; set; }

        [Input("detailFilters")]
        private List<Inputs.GetSlosDetailFilterArgs>? _detailFilters;
        public List<Inputs.GetSlosDetailFilterArgs> DetailFilters
        {
            get => _detailFilters ?? (_detailFilters = new List<Inputs.GetSlosDetailFilterArgs>());
            set => _detailFilters = value;
        }

        public GetSlosArgs()
        {
        }
        public static new GetSlosArgs Empty => new GetSlosArgs();
    }

    public sealed class GetSlosInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("dataset")]
        public Input<string>? Dataset { get; set; }

        [Input("detailFilters")]
        private InputList<Inputs.GetSlosDetailFilterInputArgs>? _detailFilters;
        public InputList<Inputs.GetSlosDetailFilterInputArgs> DetailFilters
        {
            get => _detailFilters ?? (_detailFilters = new InputList<Inputs.GetSlosDetailFilterInputArgs>());
            set => _detailFilters = value;
        }

        public GetSlosInvokeArgs()
        {
        }
        public static new GetSlosInvokeArgs Empty => new GetSlosInvokeArgs();
    }


    [OutputType]
    public sealed class GetSlosResult
    {
        public readonly string? Dataset;
        public readonly ImmutableArray<Outputs.GetSlosDetailFilterResult> DetailFilters;
        public readonly string Id;
        public readonly ImmutableArray<string> Ids;

        [OutputConstructor]
        private GetSlosResult(
            string? dataset,

            ImmutableArray<Outputs.GetSlosDetailFilterResult> detailFilters,

            string id,

            ImmutableArray<string> ids)
        {
            Dataset = dataset;
            DetailFilters = detailFilters;
            Id = id;
            Ids = ids;
        }
    }
}
