// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio
{
    [HoneycombioResourceType("honeycombio:index/msteamsRecipient:MsteamsRecipient")]
    public partial class MsteamsRecipient : global::Pulumi.CustomResource
    {
        [Output("msteamsRecipientId")]
        public Output<string> MsteamsRecipientId { get; private set; } = null!;

        /// <summary>
        /// The name of the recipient.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The Incoming Webhook URL to send the notification to
        /// </summary>
        [Output("url")]
        public Output<string> Url { get; private set; } = null!;


        /// <summary>
        /// Create a MsteamsRecipient resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public MsteamsRecipient(string name, MsteamsRecipientArgs args, CustomResourceOptions? options = null)
            : base("honeycombio:index/msteamsRecipient:MsteamsRecipient", name, args ?? new MsteamsRecipientArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private MsteamsRecipient(string name, Input<string> id, MsteamsRecipientState? state = null, CustomResourceOptions? options = null)
            : base("honeycombio:index/msteamsRecipient:MsteamsRecipient", name, state, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing MsteamsRecipient resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static MsteamsRecipient Get(string name, Input<string> id, MsteamsRecipientState? state = null, CustomResourceOptions? options = null)
        {
            return new MsteamsRecipient(name, id, state, options);
        }
    }

    public sealed class MsteamsRecipientArgs : global::Pulumi.ResourceArgs
    {
        [Input("msteamsRecipientId")]
        public Input<string>? MsteamsRecipientId { get; set; }

        /// <summary>
        /// The name of the recipient.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The Incoming Webhook URL to send the notification to
        /// </summary>
        [Input("url", required: true)]
        public Input<string> Url { get; set; } = null!;

        public MsteamsRecipientArgs()
        {
        }
        public static new MsteamsRecipientArgs Empty => new MsteamsRecipientArgs();
    }

    public sealed class MsteamsRecipientState : global::Pulumi.ResourceArgs
    {
        [Input("msteamsRecipientId")]
        public Input<string>? MsteamsRecipientId { get; set; }

        /// <summary>
        /// The name of the recipient.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The Incoming Webhook URL to send the notification to
        /// </summary>
        [Input("url")]
        public Input<string>? Url { get; set; }

        public MsteamsRecipientState()
        {
        }
        public static new MsteamsRecipientState Empty => new MsteamsRecipientState();
    }
}
