// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio
{
    [HoneycombioResourceType("honeycombio:index/msteamsWorkflowRecipient:MsteamsWorkflowRecipient")]
    public partial class MsteamsWorkflowRecipient : global::Pulumi.CustomResource
    {
        [Output("msteamsWorkflowRecipientId")]
        public Output<string> MsteamsWorkflowRecipientId { get; private set; } = null!;

        /// <summary>
        /// The name of the recipient.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The Teams Workflow URL to send the notification to.
        /// </summary>
        [Output("url")]
        public Output<string> Url { get; private set; } = null!;


        /// <summary>
        /// Create a MsteamsWorkflowRecipient resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public MsteamsWorkflowRecipient(string name, MsteamsWorkflowRecipientArgs args, CustomResourceOptions? options = null)
            : base("honeycombio:index/msteamsWorkflowRecipient:MsteamsWorkflowRecipient", name, args ?? new MsteamsWorkflowRecipientArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private MsteamsWorkflowRecipient(string name, Input<string> id, MsteamsWorkflowRecipientState? state = null, CustomResourceOptions? options = null)
            : base("honeycombio:index/msteamsWorkflowRecipient:MsteamsWorkflowRecipient", name, state, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing MsteamsWorkflowRecipient resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static MsteamsWorkflowRecipient Get(string name, Input<string> id, MsteamsWorkflowRecipientState? state = null, CustomResourceOptions? options = null)
        {
            return new MsteamsWorkflowRecipient(name, id, state, options);
        }
    }

    public sealed class MsteamsWorkflowRecipientArgs : global::Pulumi.ResourceArgs
    {
        [Input("msteamsWorkflowRecipientId")]
        public Input<string>? MsteamsWorkflowRecipientId { get; set; }

        /// <summary>
        /// The name of the recipient.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The Teams Workflow URL to send the notification to.
        /// </summary>
        [Input("url", required: true)]
        public Input<string> Url { get; set; } = null!;

        public MsteamsWorkflowRecipientArgs()
        {
        }
        public static new MsteamsWorkflowRecipientArgs Empty => new MsteamsWorkflowRecipientArgs();
    }

    public sealed class MsteamsWorkflowRecipientState : global::Pulumi.ResourceArgs
    {
        [Input("msteamsWorkflowRecipientId")]
        public Input<string>? MsteamsWorkflowRecipientId { get; set; }

        /// <summary>
        /// The name of the recipient.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The Teams Workflow URL to send the notification to.
        /// </summary>
        [Input("url")]
        public Input<string>? Url { get; set; }

        public MsteamsWorkflowRecipientState()
        {
        }
        public static new MsteamsWorkflowRecipientState Empty => new MsteamsWorkflowRecipientState();
    }
}
