// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio
{
    [HoneycombioResourceType("honeycombio:index/query:Query")]
    public partial class Query : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The dataset this Query is associated with. If not set, it will be Environment-wide.
        /// </summary>
        [Output("dataset")]
        public Output<string> Dataset { get; private set; } = null!;

        /// <summary>
        /// A JSON object describing the query according to the Query Specification. While the JSON can be constructed manually, it
        /// is easiest to use the `honeycombio.getQuerySpecification` data source.
        /// </summary>
        [Output("queryJson")]
        public Output<string> QueryJson { get; private set; } = null!;


        /// <summary>
        /// Create a Query resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Query(string name, QueryArgs args, CustomResourceOptions? options = null)
            : base("honeycombio:index/query:Query", name, args ?? new QueryArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private Query(string name, Input<string> id, QueryState? state = null, CustomResourceOptions? options = null)
            : base("honeycombio:index/query:Query", name, state, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Query resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Query Get(string name, Input<string> id, QueryState? state = null, CustomResourceOptions? options = null)
        {
            return new Query(name, id, state, options);
        }
    }

    public sealed class QueryArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The dataset this Query is associated with. If not set, it will be Environment-wide.
        /// </summary>
        [Input("dataset")]
        public Input<string>? Dataset { get; set; }

        /// <summary>
        /// A JSON object describing the query according to the Query Specification. While the JSON can be constructed manually, it
        /// is easiest to use the `honeycombio.getQuerySpecification` data source.
        /// </summary>
        [Input("queryJson", required: true)]
        public Input<string> QueryJson { get; set; } = null!;

        public QueryArgs()
        {
        }
        public static new QueryArgs Empty => new QueryArgs();
    }

    public sealed class QueryState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The dataset this Query is associated with. If not set, it will be Environment-wide.
        /// </summary>
        [Input("dataset")]
        public Input<string>? Dataset { get; set; }

        /// <summary>
        /// A JSON object describing the query according to the Query Specification. While the JSON can be constructed manually, it
        /// is easiest to use the `honeycombio.getQuerySpecification` data source.
        /// </summary>
        [Input("queryJson")]
        public Input<string>? QueryJson { get; set; }

        public QueryState()
        {
        }
        public static new QueryState Empty => new QueryState();
    }
}
