// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Outputs
{

    [OutputType]
    public sealed class BoardQueryGraphSetting
    {
        /// <summary>
        /// Disable the overlay of Markers on the graph.
        /// </summary>
        public readonly bool? HideMarkers;
        /// <summary>
        /// Set the graph's Y-axis to a logarithmic scale.
        /// </summary>
        public readonly bool? LogScale;
        /// <summary>
        /// Enable interpolatation between datapoints when the intervening time buckets have no matching events.
        /// </summary>
        public readonly bool? OmitMissingValues;
        /// <summary>
        /// Allow charts to be overlaid when using supported Visualize operators.
        /// </summary>
        public readonly bool? OverlaidCharts;
        /// <summary>
        /// Enable the display of groups as stacked colored area under their line graphs.
        /// </summary>
        public readonly bool? StackedGraphs;
        /// <summary>
        /// Set the graph's X-axis to UTC.
        /// </summary>
        public readonly bool? UtcXaxis;

        [OutputConstructor]
        private BoardQueryGraphSetting(
            bool? hideMarkers,

            bool? logScale,

            bool? omitMissingValues,

            bool? overlaidCharts,

            bool? stackedGraphs,

            bool? utcXaxis)
        {
            HideMarkers = hideMarkers;
            LogScale = logScale;
            OmitMissingValues = omitMissingValues;
            OverlaidCharts = overlaidCharts;
            StackedGraphs = stackedGraphs;
            UtcXaxis = utcXaxis;
        }
    }
}
