// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Outputs
{

    [OutputType]
    public sealed class FlexibleBoardPanel
    {
        /// <summary>
        /// Manages the position of the panel on the board.
        /// </summary>
        public readonly ImmutableArray<Outputs.FlexibleBoardPanelPosition> Positions;
        /// <summary>
        /// A query panel to be displayed on the Board.
        /// </summary>
        public readonly ImmutableArray<Outputs.FlexibleBoardPanelQueryPanel> QueryPanels;
        /// <summary>
        /// A Service Level Objective(SLO) panel to be displayed on the Board.
        /// </summary>
        public readonly ImmutableArray<Outputs.FlexibleBoardPanelSloPanel> SloPanels;
        /// <summary>
        /// The panel type, either "query" or "slo".
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private FlexibleBoardPanel(
            ImmutableArray<Outputs.FlexibleBoardPanelPosition> positions,

            ImmutableArray<Outputs.FlexibleBoardPanelQueryPanel> queryPanels,

            ImmutableArray<Outputs.FlexibleBoardPanelSloPanel> sloPanels,

            string type)
        {
            Positions = positions;
            QueryPanels = queryPanels;
            SloPanels = sloPanels;
            Type = type;
        }
    }
}
