// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Outputs
{

    [OutputType]
    public sealed class FlexibleBoardPanelQueryPanelVisualizationSettingChart
    {
        /// <summary>
        /// Index of the chart this configuration controls.
        /// </summary>
        public readonly double? ChartIndex;
        /// <summary>
        /// Type of chart (e.g., 'line', 'bar').
        /// </summary>
        public readonly string? ChartType;
        /// <summary>
        /// Omit missing values from the visualization.
        /// </summary>
        public readonly bool? OmitMissingValues;
        /// <summary>
        /// Use logarithmic scale on Y axis.
        /// </summary>
        public readonly bool? UseLogScale;

        [OutputConstructor]
        private FlexibleBoardPanelQueryPanelVisualizationSettingChart(
            double? chartIndex,

            string? chartType,

            bool? omitMissingValues,

            bool? useLogScale)
        {
            ChartIndex = chartIndex;
            ChartType = chartType;
            OmitMissingValues = omitMissingValues;
            UseLogScale = useLogScale;
        }
    }
}
