// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Outputs
{

    [OutputType]
    public sealed class GetQuerySpecificationFilterResult
    {
        /// <summary>
        /// The column to filter on.
        /// </summary>
        public readonly string Column;
        /// <summary>
        /// The operator to apply.
        /// </summary>
        public readonly string Op;
        /// <summary>
        /// The value used for the filter. Not needed if op is "exists" or "not-exists".
        /// </summary>
        public readonly string? Value;

        [OutputConstructor]
        private GetQuerySpecificationFilterResult(
            string column,

            string op,

            string? value)
        {
            Column = column;
            Op = op;
            Value = value;
        }
    }
}
