// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Outputs
{

    [OutputType]
    public sealed class GetQuerySpecificationHavingResult
    {
        /// <summary>
        /// The operator to apply.
        /// </summary>
        public readonly string CalculateOp;
        /// <summary>
        /// The column to filter on. Not allowed with "COUNT".
        /// </summary>
        public readonly string? Column;
        /// <summary>
        /// The operator to apply.
        /// </summary>
        public readonly string Op;
        /// <summary>
        /// The value used for the filter.
        /// </summary>
        public readonly double Value;

        [OutputConstructor]
        private GetQuerySpecificationHavingResult(
            string calculateOp,

            string? column,

            string op,

            double value)
        {
            CalculateOp = calculateOp;
            Column = column;
            Op = op;
            Value = value;
        }
    }
}
