// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Outputs
{

    [OutputType]
    public sealed class GetQuerySpecificationCalculatedFieldResult
    {
        /// <summary>
        /// The formula to use for the Calculated Field.
        /// </summary>
        public readonly string Expression;
        /// <summary>
        /// The name of the Calculated Field.
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private GetQuerySpecificationCalculatedFieldResult(
            string expression,

            string name)
        {
            Expression = expression;
            Name = name;
        }
    }
}
