// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Outputs
{

    [OutputType]
    public sealed class GetRecipientsDetailFilterResult
    {
        /// <summary>
        /// The name of the detail field to filter by
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The value of the detail field to match on.
        /// </summary>
        public readonly string? Value;
        /// <summary>
        /// A regular expression string to apply to the value of the detail field to match on.
        /// </summary>
        public readonly string? ValueRegex;

        [OutputConstructor]
        private GetRecipientsDetailFilterResult(
            string name,

            string? value,

            string? valueRegex)
        {
            Name = name;
            Value = value;
            ValueRegex = valueRegex;
        }
    }
}
