// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Outputs
{

    [OutputType]
    public sealed class TriggerRecipientNotificationDetail
    {
        /// <summary>
        /// The severity to set with the PagerDuty notification. If no severity is provided, 'critical' is assumed.
        /// </summary>
        public readonly string? PagerdutySeverity;
        /// <summary>
        /// The variables to set with the webhook notification.
        /// </summary>
        public readonly ImmutableArray<Outputs.TriggerRecipientNotificationDetailVariable> Variables;

        [OutputConstructor]
        private TriggerRecipientNotificationDetail(
            string? pagerdutySeverity,

            ImmutableArray<Outputs.TriggerRecipientNotificationDetailVariable> variables)
        {
            PagerdutySeverity = pagerdutySeverity;
            Variables = variables;
        }
    }
}
