// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Outputs
{

    [OutputType]
    public sealed class WebhookRecipientTemplate
    {
        /// <summary>
        /// JSON formatted string of the webhook payload
        /// </summary>
        public readonly string Body;
        /// <summary>
        /// The type of the webhook template
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private WebhookRecipientTemplate(
            string body,

            string type)
        {
            Body = body;
            Type = type;
        }
    }
}
