// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Outputs
{

    [OutputType]
    public sealed class ApiKeyPermission
    {
        /// <summary>
        /// Allow this key to create missing datasets when sending telemetry.
        /// </summary>
        public readonly bool? CreateDatasets;

        [OutputConstructor]
        private ApiKeyPermission(bool? createDatasets)
        {
            CreateDatasets = createDatasets;
        }
    }
}
