// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Outputs
{

    [OutputType]
    public sealed class BoardSlo
    {
        /// <summary>
        /// The ID of the SLO.
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private BoardSlo(string id)
        {
            Id = id;
        }
    }
}
