// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Outputs
{

    [OutputType]
    public sealed class FlexibleBoardPanelQueryPanelVisualizationSetting
    {
        public readonly ImmutableArray<Outputs.FlexibleBoardPanelQueryPanelVisualizationSettingChart> Charts;
        /// <summary>
        /// Hide comparison values.
        /// </summary>
        public readonly bool? HideCompare;
        /// <summary>
        /// Disable Graph tooltips in the results display when hovering over a graph.
        /// </summary>
        public readonly bool? HideHovers;
        /// <summary>
        /// Hide markers from appearing on graph.
        /// </summary>
        public readonly bool? HideMarkers;
        /// <summary>
        /// Combine any visualized AVG, MIN, MAX, and PERCENTILE clauses into a single chart.
        /// </summary>
        public readonly bool? PreferOverlaidCharts;
        /// <summary>
        /// Display UTC Time X-Axis or Localtime X-Axis.
        /// </summary>
        public readonly bool? UseUtcXaxis;

        [OutputConstructor]
        private FlexibleBoardPanelQueryPanelVisualizationSetting(
            ImmutableArray<Outputs.FlexibleBoardPanelQueryPanelVisualizationSettingChart> charts,

            bool? hideCompare,

            bool? hideHovers,

            bool? hideMarkers,

            bool? preferOverlaidCharts,

            bool? useUtcXaxis)
        {
            Charts = charts;
            HideCompare = hideCompare;
            HideHovers = hideHovers;
            HideMarkers = hideMarkers;
            PreferOverlaidCharts = preferOverlaidCharts;
            UseUtcXaxis = useUtcXaxis;
        }
    }
}
