// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Outputs
{

    [OutputType]
    public sealed class FlexibleBoardPanelPosition
    {
        /// <summary>
        /// The height of the panel.
        /// </summary>
        public readonly double? Height;
        /// <summary>
        /// The width of the panel.
        /// </summary>
        public readonly double? Width;
        /// <summary>
        /// The X coordinate of the panel.
        /// </summary>
        public readonly double? XCoordinate;
        /// <summary>
        /// The Y coordinate of the panel.
        /// </summary>
        public readonly double? YCoordinate;

        [OutputConstructor]
        private FlexibleBoardPanelPosition(
            double? height,

            double? width,

            double? xCoordinate,

            double? yCoordinate)
        {
            Height = height;
            Width = width;
            XCoordinate = xCoordinate;
            YCoordinate = yCoordinate;
        }
    }
}
