// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Outputs
{

    [OutputType]
    public sealed class FlexibleBoardPanelQueryPanel
    {
        /// <summary>
        /// Query annotation ID.
        /// </summary>
        public readonly string QueryAnnotationId;
        /// <summary>
        /// Query ID to be rendered in the panel.
        /// </summary>
        public readonly string QueryId;
        /// <summary>
        /// The visual style of the query (e.g., 'graph', 'combo').
        /// </summary>
        public readonly string? QueryStyle;
        public readonly ImmutableArray<Outputs.FlexibleBoardPanelQueryPanelVisualizationSetting> VisualizationSettings;

        [OutputConstructor]
        private FlexibleBoardPanelQueryPanel(
            string queryAnnotationId,

            string queryId,

            string? queryStyle,

            ImmutableArray<Outputs.FlexibleBoardPanelQueryPanelVisualizationSetting> visualizationSettings)
        {
            QueryAnnotationId = queryAnnotationId;
            QueryId = queryId;
            QueryStyle = queryStyle;
            VisualizationSettings = visualizationSettings;
        }
    }
}
