// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Outputs
{

    [OutputType]
    public sealed class FlexibleBoardPanelSloPanel
    {
        /// <summary>
        /// SLO ID to display in this panel.
        /// </summary>
        public readonly string SloId;

        [OutputConstructor]
        private FlexibleBoardPanelSloPanel(string sloId)
        {
            SloId = sloId;
        }
    }
}
