// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Outputs
{

    [OutputType]
    public sealed class GetAuthMetadataEnvironmentResult
    {
        /// <summary>
        /// Whether the Environment is a Classic Environment.
        /// </summary>
        public readonly bool Classic;
        /// <summary>
        /// The name of the Environment. For Classic environments, this will be null.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The slug of the Environment. For Classic environments, this will be null.
        /// </summary>
        public readonly string Slug;

        [OutputConstructor]
        private GetAuthMetadataEnvironmentResult(
            bool classic,

            string name,

            string slug)
        {
            Classic = classic;
            Name = name;
            Slug = slug;
        }
    }
}
