// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Outputs
{

    [OutputType]
    public sealed class GetAuthMetadataTeamResult
    {
        /// <summary>
        /// The name of the Team.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The slug of the Team.
        /// </summary>
        public readonly string Slug;

        [OutputConstructor]
        private GetAuthMetadataTeamResult(
            string name,

            string slug)
        {
            Name = name;
            Slug = slug;
        }
    }
}
