// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Outputs
{

    [OutputType]
    public sealed class GetAuthMetadataApiKeyAccessResult
    {
        /// <summary>
        /// Whether this API key can create and manage Boards.
        /// </summary>
        public readonly bool Boards;
        /// <summary>
        /// Whether this API key can create and manage Queries, Columns, Derived Columns, and Query Annotations.
        /// </summary>
        public readonly bool Columns;
        /// <summary>
        /// Whether this API key can create and manage Datasets.
        /// </summary>
        public readonly bool Datasets;
        /// <summary>
        /// Whether this API key can send events to Honeycomb.
        /// </summary>
        public readonly bool Events;
        /// <summary>
        /// Whether this API key can create and manage Markers.
        /// </summary>
        public readonly bool Markers;
        /// <summary>
        /// Whether this API key can execute existing Queries via the Query Data API.
        /// </summary>
        public readonly bool Queries;
        /// <summary>
        /// Whether this API key can create and manage Recipients.
        /// </summary>
        public readonly bool Recipients;
        /// <summary>
        /// Whether this API key can create and manage SLOs and Burn Alerts.
        /// </summary>
        public readonly bool Slos;
        /// <summary>
        /// Whether this API key can create and manage Triggers.
        /// </summary>
        public readonly bool Triggers;

        [OutputConstructor]
        private GetAuthMetadataApiKeyAccessResult(
            bool boards,

            bool columns,

            bool datasets,

            bool events,

            bool markers,

            bool queries,

            bool recipients,

            bool slos,

            bool triggers)
        {
            Boards = boards;
            Columns = columns;
            Datasets = datasets;
            Events = events;
            Markers = markers;
            Queries = queries;
            Recipients = recipients;
            Slos = slos;
            Triggers = triggers;
        }
    }
}
