// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Outputs
{

    [OutputType]
    public sealed class GetQuerySpecificationOrderResult
    {
        /// <summary>
        /// Either a column present in "breakdown" or a column that "op" applies to.
        /// </summary>
        public readonly string? Column;
        /// <summary>
        /// The operator to apply.
        /// </summary>
        public readonly string? Op;
        /// <summary>
        /// The sort order to apply.
        /// </summary>
        public readonly string? Order;

        [OutputConstructor]
        private GetQuerySpecificationOrderResult(
            string? column,

            string? op,

            string? order)
        {
            Column = column;
            Op = op;
            Order = order;
        }
    }
}
