// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Outputs
{

    [OutputType]
    public sealed class GetQuerySpecificationCalculationResult
    {
        /// <summary>
        /// The column to apply the operator on. Not allowed with "COUNT" or "CONCURRENCY", required for all other operators.
        /// </summary>
        public readonly string? Column;
        /// <summary>
        /// The operatior to apply.
        /// </summary>
        public readonly string Op;

        [OutputConstructor]
        private GetQuerySpecificationCalculationResult(
            string? column,

            string op)
        {
            Column = column;
            Op = op;
        }
    }
}
