// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Outputs
{

    [OutputType]
    public sealed class TriggerEvaluationSchedule
    {
        /// <summary>
        /// The days of the week to evaluate the trigger on
        /// </summary>
        public readonly ImmutableArray<string> DaysOfWeeks;
        /// <summary>
        /// UTC time to stop evaluating the trigger in HH:mm format
        /// </summary>
        public readonly string EndTime;
        /// <summary>
        /// UTC time to start evaluating the trigger in HH:mm format
        /// </summary>
        public readonly string StartTime;

        [OutputConstructor]
        private TriggerEvaluationSchedule(
            ImmutableArray<string> daysOfWeeks,

            string endTime,

            string startTime)
        {
            DaysOfWeeks = daysOfWeeks;
            EndTime = endTime;
            StartTime = startTime;
        }
    }
}
