// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Outputs
{

    [OutputType]
    public sealed class TriggerThreshold
    {
        /// <summary>
        /// The number of times the threshold is met before an alert is sent. Defaults to 1.
        /// </summary>
        public readonly double? ExceededLimit;
        /// <summary>
        /// The operator to apply.
        /// </summary>
        public readonly string Op;
        /// <summary>
        /// The value to be used with the operator.
        /// </summary>
        public readonly double Value;

        [OutputConstructor]
        private TriggerThreshold(
            double? exceededLimit,

            string op,

            double value)
        {
            ExceededLimit = exceededLimit;
            Op = op;
            Value = value;
        }
    }
}
