// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Outputs
{

    [OutputType]
    public sealed class TriggerBaselineDetail
    {
        /// <summary>
        /// What previous time period to evaluate against: 1 hour, 1 day, 1 week, or 4 weeks.
        /// </summary>
        public readonly double OffsetMinutes;
        /// <summary>
        /// Whether to use an absolute value or percentage delta.
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private TriggerBaselineDetail(
            double offsetMinutes,

            string type)
        {
            OffsetMinutes = offsetMinutes;
            Type = type;
        }
    }
}
