// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Outputs
{

    [OutputType]
    public sealed class WebhookRecipientHeader
    {
        /// <summary>
        /// The name or key for the header
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Value for the header
        /// </summary>
        public readonly string? Value;

        [OutputConstructor]
        private WebhookRecipientHeader(
            string name,

            string? value)
        {
            Name = name;
            Value = value;
        }
    }
}
