// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Outputs
{

    [OutputType]
    public sealed class WebhookRecipientVariable
    {
        /// <summary>
        /// An optional default value for the variable
        /// </summary>
        public readonly string? DefaultValue;
        /// <summary>
        /// The name of the variable
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private WebhookRecipientVariable(
            string? defaultValue,

            string name)
        {
            DefaultValue = defaultValue;
            Name = name;
        }
    }
}
