// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Inputs
{

    public sealed class ApiKeyPermissionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Allow this key to create missing datasets when sending telemetry.
        /// </summary>
        [Input("createDatasets")]
        public Input<bool>? CreateDatasets { get; set; }

        public ApiKeyPermissionArgs()
        {
        }
        public static new ApiKeyPermissionArgs Empty => new ApiKeyPermissionArgs();
    }
}
