// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Inputs
{

    public sealed class BoardQueryGraphSettingArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Disable the overlay of Markers on the graph.
        /// </summary>
        [Input("hideMarkers")]
        public Input<bool>? HideMarkers { get; set; }

        /// <summary>
        /// Set the graph's Y-axis to a logarithmic scale.
        /// </summary>
        [Input("logScale")]
        public Input<bool>? LogScale { get; set; }

        /// <summary>
        /// Enable interpolatation between datapoints when the intervening time buckets have no matching events.
        /// </summary>
        [Input("omitMissingValues")]
        public Input<bool>? OmitMissingValues { get; set; }

        /// <summary>
        /// Allow charts to be overlaid when using supported Visualize operators.
        /// </summary>
        [Input("overlaidCharts")]
        public Input<bool>? OverlaidCharts { get; set; }

        /// <summary>
        /// Enable the display of groups as stacked colored area under their line graphs.
        /// </summary>
        [Input("stackedGraphs")]
        public Input<bool>? StackedGraphs { get; set; }

        /// <summary>
        /// Set the graph's X-axis to UTC.
        /// </summary>
        [Input("utcXaxis")]
        public Input<bool>? UtcXaxis { get; set; }

        public BoardQueryGraphSettingArgs()
        {
        }
        public static new BoardQueryGraphSettingArgs Empty => new BoardQueryGraphSettingArgs();
    }
}
