// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Inputs
{

    public sealed class GetAuthMetadataEnvironmentInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether the Environment is a Classic Environment.
        /// </summary>
        [Input("classic", required: true)]
        public Input<bool> Classic { get; set; } = null!;

        /// <summary>
        /// The name of the Environment. For Classic environments, this will be null.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// The slug of the Environment. For Classic environments, this will be null.
        /// </summary>
        [Input("slug", required: true)]
        public Input<string> Slug { get; set; } = null!;

        public GetAuthMetadataEnvironmentInputArgs()
        {
        }
        public static new GetAuthMetadataEnvironmentInputArgs Empty => new GetAuthMetadataEnvironmentInputArgs();
    }
}
