// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Inputs
{

    public sealed class GetAuthMetadataTeamArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the Team.
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        /// <summary>
        /// The slug of the Team.
        /// </summary>
        [Input("slug", required: true)]
        public string Slug { get; set; } = null!;

        public GetAuthMetadataTeamArgs()
        {
        }
        public static new GetAuthMetadataTeamArgs Empty => new GetAuthMetadataTeamArgs();
    }
}
