// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Inputs
{

    public sealed class GetDatasetsDetailFilterInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The field to filter by (e.g., 'name', 'id', 'description', etc.).
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// The comparison operator. The default is 'equals'.
        /// </summary>
        [Input("operator")]
        public Input<string>? Operator { get; set; }

        /// <summary>
        /// The value of the detail field to match on.
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        /// <summary>
        /// A regular expression string to apply to the value of the detail field to match on.
        /// </summary>
        [Input("valueRegex")]
        public Input<string>? ValueRegex { get; set; }

        public GetDatasetsDetailFilterInputArgs()
        {
        }
        public static new GetDatasetsDetailFilterInputArgs Empty => new GetDatasetsDetailFilterInputArgs();
    }
}
