// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Inputs
{

    public sealed class GetQuerySpecificationOrderInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Either a column present in "breakdown" or a column that "op" applies to.
        /// </summary>
        [Input("column")]
        public Input<string>? Column { get; set; }

        /// <summary>
        /// The operator to apply.
        /// </summary>
        [Input("op")]
        public Input<string>? Op { get; set; }

        /// <summary>
        /// The sort order to apply.
        /// </summary>
        [Input("order")]
        public Input<string>? Order { get; set; }

        public GetQuerySpecificationOrderInputArgs()
        {
        }
        public static new GetQuerySpecificationOrderInputArgs Empty => new GetQuerySpecificationOrderInputArgs();
    }
}
