// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Inputs
{

    public sealed class GetQuerySpecificationCalculatedFieldArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The formula to use for the Calculated Field.
        /// </summary>
        [Input("expression", required: true)]
        public string Expression { get; set; } = null!;

        /// <summary>
        /// The name of the Calculated Field.
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetQuerySpecificationCalculatedFieldArgs()
        {
        }
        public static new GetQuerySpecificationCalculatedFieldArgs Empty => new GetQuerySpecificationCalculatedFieldArgs();
    }
}
