// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Inputs
{

    public sealed class GetQuerySpecificationCalculationInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The column to apply the operator on. Not allowed with "COUNT" or "CONCURRENCY", required for all other operators.
        /// </summary>
        [Input("column")]
        public Input<string>? Column { get; set; }

        /// <summary>
        /// The operatior to apply.
        /// </summary>
        [Input("op", required: true)]
        public Input<string> Op { get; set; } = null!;

        public GetQuerySpecificationCalculationInputArgs()
        {
        }
        public static new GetQuerySpecificationCalculationInputArgs Empty => new GetQuerySpecificationCalculationInputArgs();
    }
}
