// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Inputs
{

    public sealed class GetQuerySpecificationCalculatedFieldInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The formula to use for the Calculated Field.
        /// </summary>
        [Input("expression", required: true)]
        public Input<string> Expression { get; set; } = null!;

        /// <summary>
        /// The name of the Calculated Field.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetQuerySpecificationCalculatedFieldInputArgs()
        {
        }
        public static new GetQuerySpecificationCalculatedFieldInputArgs Empty => new GetQuerySpecificationCalculatedFieldInputArgs();
    }
}
