// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Inputs
{

    public sealed class GetRecipientsDetailFilterInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the detail field to filter by
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// The value of the detail field to match on.
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        /// <summary>
        /// A regular expression string to apply to the value of the detail field to match on.
        /// </summary>
        [Input("valueRegex")]
        public Input<string>? ValueRegex { get; set; }

        public GetRecipientsDetailFilterInputArgs()
        {
        }
        public static new GetRecipientsDetailFilterInputArgs Empty => new GetRecipientsDetailFilterInputArgs();
    }
}
