// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Inputs
{

    public sealed class TriggerEvaluationScheduleGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("daysOfWeeks", required: true)]
        private InputList<string>? _daysOfWeeks;

        /// <summary>
        /// The days of the week to evaluate the trigger on
        /// </summary>
        public InputList<string> DaysOfWeeks
        {
            get => _daysOfWeeks ?? (_daysOfWeeks = new InputList<string>());
            set => _daysOfWeeks = value;
        }

        /// <summary>
        /// UTC time to stop evaluating the trigger in HH:mm format
        /// </summary>
        [Input("endTime", required: true)]
        public Input<string> EndTime { get; set; } = null!;

        /// <summary>
        /// UTC time to start evaluating the trigger in HH:mm format
        /// </summary>
        [Input("startTime", required: true)]
        public Input<string> StartTime { get; set; } = null!;

        public TriggerEvaluationScheduleGetArgs()
        {
        }
        public static new TriggerEvaluationScheduleGetArgs Empty => new TriggerEvaluationScheduleGetArgs();
    }
}
