// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Inputs
{

    public sealed class TriggerThresholdArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The number of times the threshold is met before an alert is sent. Defaults to 1.
        /// </summary>
        [Input("exceededLimit")]
        public Input<double>? ExceededLimit { get; set; }

        /// <summary>
        /// The operator to apply.
        /// </summary>
        [Input("op", required: true)]
        public Input<string> Op { get; set; } = null!;

        /// <summary>
        /// The value to be used with the operator.
        /// </summary>
        [Input("value", required: true)]
        public Input<double> Value { get; set; } = null!;

        public TriggerThresholdArgs()
        {
        }
        public static new TriggerThresholdArgs Empty => new TriggerThresholdArgs();
    }
}
