// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycombio.Inputs
{

    public sealed class WebhookRecipientTemplateGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// JSON formatted string of the webhook payload
        /// </summary>
        [Input("body", required: true)]
        public Input<string> Body { get; set; } = null!;

        /// <summary>
        /// The type of the webhook template
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public WebhookRecipientTemplateGetArgs()
        {
        }
        public static new WebhookRecipientTemplateGetArgs Empty => new WebhookRecipientTemplateGetArgs();
    }
}
